author: Akis Kesoglou
author_url: http://twitter.com/dfunckt
copyright: '© 2019 Akis Kesoglou. Licensed under the MIT license.'

clean: true
theme: fullwidth
use_safe_filenames: true
hide_documentation_coverage: true
undocumented_text: ''
exclude:
  - "/*/Channel/*"
  - "/*/Future/*"
  - "/*/Internal/*"
  - "/*/Sink/*"
  - "/*/Stream/*"
  - "/*/Private.swift"
  - "Package.swift"

custom_categories:
  - name: Core Types
    children:
    - FutureProtocol
    - StreamProtocol
    - SinkProtocol
    - ChannelProtocol
    - ExecutorProtocol
    - Task

  - name: Core Namespaces
    children:
    - Future
    - Stream
    - Sink
    - Channel

  - name: Futures
    children:
    - FutureConvertible
    - Promise
    - Deferred
    - AnyFuture
    - AnyResultFuture
    - ResultFuture

  - name: Streams
    children:
    - StreamConvertible
    - AnyStream
    - AnyMulticastStream
    - AnySharedStream
    - AnyResultStream
    - ResultStream

  - name: Sinks
    children:
    - SinkConvertible
    - AnySink

  - name: Executors
    children:
    - BlockingExecutor
    - ExecutorError
    - QueueExecutor
    - RunLoopExecutor
    - ThreadExecutor

  - name: Supporting Types
    children:
    - Context
    - Poll
    - WakerProtocol
    - AnyWaker
    - Cancellable
    - AnyCancellable
    - Either
    - EitherConvertible

  - name: Primitives
    children:
    - Atomic
    - AtomicEnum
    - AtomicBitset
    - AtomicReference
    - AtomicBool
    - AtomicBoolPointer
    - AtomicInt
    - AtomicIntPointer
    - AtomicInt8
    - AtomicInt8Pointer
    - AtomicInt16
    - AtomicInt16Pointer
    - AtomicInt32
    - AtomicInt32Pointer
    - AtomicInt64
    - AtomicInt64Pointer
    - AtomicUInt
    - AtomicUIntPointer
    - AtomicUInt8
    - AtomicUInt8Pointer
    - AtomicUInt16
    - AtomicUInt16Pointer
    - AtomicUInt32
    - AtomicUInt32Pointer
    - AtomicUInt64
    - AtomicUInt64Pointer
    - AtomicUSize

  - name: Bounded Queues
    children:
    - AtomicQueueProtocol
    - AtomicSPSCQueue
    - AtomicSPMCQueue
    - AtomicMPSCQueue
    - AtomicMPMCQueue

  - name: Unbounded Queues
    children:
    - AtomicUnboundedQueueProtocol
    - AtomicUnboundedMPSCQueue
    - AtomicUnboundedSPSCQueue

  - name: Locking
    children:
    - LockingProtocol
    - PosixLock
    - UnfairLock
    - SpinLock
    - Mutex

  - name: Thread
    children:
    - ThreadLocal

  - name: Helpers
    children:
    - Backoff
