language: generic

addons:
  apt:
    packages:
      - build-essential
      - clang
      - curl
      - gpg-agent
      - libcurl4
      - libicu-dev
      - libpython2.7
      - libxml2
      - libz-dev
      - pkg-config
      - software-properties-common
  homebrew:
    packages:
      - swiftformat
      - swiftlint
  ssh_known_hosts: github.com

stages:
  - pretest
  - test
  - name: release
    if: type != pull_request AND branch = master AND tag IS present

jobs:
  include:
    - stage: pretest
      name: Check commit
      os: osx
      osx_image: xcode11
      script: make pretest

    - stage: test
      name: Ubuntu 18.04 / Swift 5.1
      os: linux
      dist: bionic
      before_install: export PATH="${TRAVIS_BUILD_DIR}/usr/bin":"${PATH}"
      install: make toolchain-bionic
      script: make test

    - stage: test
      name: macOS 10.14 / Xcode 11.0
      os: osx
      osx_image: xcode11
      script: make test

    - stage: release
      name: Documentation
      os: osx
      osx_image: xcode11
      before_install:
        - openssl aes-256-cbc -K $encrypted_2ed176c0e455_key -iv $encrypted_2ed176c0e455_iv -in ./Scripts/travis-deploy.enc -out /tmp/deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_key
        - ssh-add /tmp/deploy_key
      install: sudo gem install --no-document jazzy
      script: make docs
