name: Release

on:
  release:
    types: published

jobs:
  docs:
    name: Documentation
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - run: sudo gem install --no-document jazzy
    - run: make docs
      env:
        CI: 'true'
